I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 30, in script
    $ etat = false
  File "game/script.rpy", line 30, in <module>
    $ etat = false
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 30, in script
    $ etat = false
  File "C:\Users\rudyf\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\rudyf\Desktop\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 30, in <module>
    $ etat = false
NameError: name 'false' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Crea Num 1.0
Mon Nov 28 14:46:22 2022
